add data cleaning full and final script and .gitignore

diff --git a/analyse b/analyse
--- a/analyse
+++ b/analyse
@@ -1,19 +1,51 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# Name: Atharva Adhikari
+# ID: 25049366
+# Version Number: 6
+# Date of completion: 22 May 2026
+
+if [[ $# -ne 1 ]]; then
+    echo "ERROR: No input CSV file provided"
+    exit 1
+fi
 
 INPUT_FILE="$1"
+
+if [[ ! -f "$INPUT_FILE" ]]; then
+    echo "ERROR: Input file not found in the current directory"
+    exit 1
+fi
+
+if [[ "$INPUT_FILE" != *.csv ]]; then
+    echo "ERROR: Input file expected in a CSV format"
+    exit 1
+fi
+
+if [[ ! -s "$INPUT_FILE" ]]; then
+    echo "ERROR: Empty file provided"
+    exit 1
+fi
 
 awk -F',' '
 
 BEGIN {
+    OFS = ","
+
     maxFreq = 0
     maxDislikes = -1
     maxEngagement = -1
     minSentiment = 999999
     totalViews = 0
     count = 0
+    maxEngagementSet = 0
+    minSentimentSet = 0
 }
 
 NR > 1 {
+
+    if ($3 <= 0 || $4 <= 0 || $5 <= 0)
+        next
 
     video_id = $1
     publish_date = $2
@@ -21,14 +53,11 @@ NR > 1 {
     likes = $4
     dislikes = $5
 
-    # Most frequent video
     freq[video_id]++
 
-    # Mean views
     totalViews += views
     count++
 
-    # Maximum dislikes
     if (dislikes > maxDislikes) {
 
         maxDislikes = dislikes
@@ -43,13 +72,12 @@ NR > 1 {
         maxDislikeVideos[video_id] = 1
     }
 
-    # Engagement rate
-    # (likes + dislikes) / views
     engagement = (likes + dislikes) / views
 
-    if (engagement > maxEngagement) {
+    if (!maxEngagementSet || engagement > maxEngagement) {
 
         maxEngagement = engagement
+        maxEngagementSet = 1
 
         delete engagementVideos
 
@@ -61,13 +89,12 @@ NR > 1 {
         engagementVideos[video_id "," publish_date] = 1
     }
 
-    # Net sentiment rate
-    # (likes - dislikes) / views
     sentiment = (likes - dislikes) / views
 
-    if (sentiment < minSentiment) {
+    if (!minSentimentSet || sentiment < minSentiment) {
 
         minSentiment = sentiment
+        minSentimentSet = 1
 
         delete sentimentVideos
 
@@ -82,56 +109,93 @@ NR > 1 {
 
 END {
 
-    # Most frequent video
-
-
     for (id in freq) {
 
-        if (freq[id] > maxFreq) {
-
+        if (freq[id] > maxFreq)
             maxFreq = freq[id]
-        }
     }
+
+    printf "Most frequent video, ID: "
+
+    sep = ""
 
     for (id in freq) {
 
         if (freq[id] == maxFreq) {
 
-            print "Most frequent video, ID:", id
+            printf "%s%s", sep, id
+            sep = ", "
         }
     }
 
-    # Mean views
+    printf "\n"
 
     meanViews = totalViews / count
 
     printf "Mean number of views: %.2f\n", meanViews
 
-    # Maximum dislikes
+    printf "Max dislikes video, ID: "
+
+    sep = ""
 
     for (id in maxDislikeVideos) {
 
-        print "Max dislikes video, ID:", id
+        printf "%s%s", sep, id
+        sep = ", "
     }
 
+    printf "\n"
 
-    # Highest engagement rate
+    printf "Highest engagement rate video, ID: "
 
+    sep = ""
 
     for (entry in engagementVideos) {
 
         split(entry, arr, ",")
 
-        print "Highest engagement rate video, ID:", arr[1] ", dated:", arr[2]
+        printf "%s%s", sep, arr[1]
+        sep = ", "
     }
 
-    # Least sentiment rate
+    printf ", dated: "
+
+    sep = ""
+
+    for (entry in engagementVideos) {
+
+        split(entry, arr, ",")
+
+        printf "%s%s", sep, arr[2]
+        sep = ", "
+    }
+
+    printf "\n"
+
+    printf "Least sentiment rate video, ID: "
+
+    sep = ""
 
     for (entry in sentimentVideos) {
 
         split(entry, arr, ",")
 
-        print "Least sentiment rate video, ID:", arr[1] ", dated:", arr[2]
+        printf "%s%s", sep, arr[1]
+        sep = ", "
     }
+
+    printf ", dated: "
+
+    sep = ""
+
+    for (entry in sentimentVideos) {
+
+        split(entry, arr, ",")
+
+        printf "%s%s", sep, arr[2]
+        sep = ", "
+    }
+
+    printf "\n"
 }
 ' "$INPUT_FILE"
